require('dotenv').config();
const db = require('../config/database');

// Popular kids TV shows, movies, and books for autocomplete
const seedData = [
  // TV Shows (popularity_rank 1-200)
  { title: 'Bluey', content_type: 'tv_show', popularity_rank: 1 },
  { title: 'Paw Patrol', content_type: 'tv_show', popularity_rank: 2 },
  { title: 'Cocomelon', content_type: 'tv_show', popularity_rank: 3 },
  { title: 'Peppa Pig', content_type: 'tv_show', popularity_rank: 4 },
  { title: 'SpongeBob SquarePants', content_type: 'tv_show', popularity_rank: 5 },
  { title: 'Stranger Things', content_type: 'tv_show', popularity_rank: 6 },
  { title: 'Wednesday', content_type: 'tv_show', popularity_rank: 7 },
  { title: 'Avatar: The Last Airbender', content_type: 'tv_show', popularity_rank: 8 },
  { title: 'Gravity Falls', content_type: 'tv_show', popularity_rank: 9 },
  { title: 'The Owl House', content_type: 'tv_show', popularity_rank: 10 },
  { title: 'Amphibia', content_type: 'tv_show', popularity_rank: 11 },
  { title: 'Dead End: Paranormal Park', content_type: 'tv_show', popularity_rank: 12 },
  { title: 'Big City Greens', content_type: 'tv_show', popularity_rank: 13 },
  { title: 'The Ghost and Molly McGee', content_type: 'tv_show', popularity_rank: 14 },
  { title: 'Miraculous: Tales of Ladybug & Cat Noir', content_type: 'tv_show', popularity_rank: 15 },
  { title: 'Teen Titans Go!', content_type: 'tv_show', popularity_rank: 16 },
  { title: 'Steven Universe', content_type: 'tv_show', popularity_rank: 17 },
  { title: 'Adventure Time', content_type: 'tv_show', popularity_rank: 18 },
  { title: 'The Amazing World of Gumball', content_type: 'tv_show', popularity_rank: 19 },
  { title: 'Regular Show', content_type: 'tv_show', popularity_rank: 20 },
  { title: 'Kipo and the Age of Wonderbeasts', content_type: 'tv_show', popularity_rank: 21 },
  { title: 'She-Ra and the Princesses of Power', content_type: 'tv_show', popularity_rank: 22 },
  { title: 'The Dragon Prince', content_type: 'tv_show', popularity_rank: 23 },
  { title: 'Hilda', content_type: 'tv_show', popularity_rank: 24 },
  { title: 'The Loud House', content_type: 'tv_show', popularity_rank: 25 },
  { title: 'Daniel Tiger\'s Neighborhood', content_type: 'tv_show', popularity_rank: 26 },
  { title: 'Doc McStuffins', content_type: 'tv_show', popularity_rank: 27 },
  { title: 'Mickey Mouse Clubhouse', content_type: 'tv_show', popularity_rank: 28 },
  { title: 'Dora the Explorer', content_type: 'tv_show', popularity_rank: 29 },
  { title: 'Blue\'s Clues & You!', content_type: 'tv_show', popularity_rank: 30 },
  { title: 'Sesame Street', content_type: 'tv_show', popularity_rank: 31 },
  { title: 'Mister Rogers\' Neighborhood', content_type: 'tv_show', popularity_rank: 32 },
  { title: 'Arthur', content_type: 'tv_show', popularity_rank: 33 },
  { title: 'Wild Kratts', content_type: 'tv_show', popularity_rank: 34 },
  { title: 'Octonauts', content_type: 'tv_show', popularity_rank: 35 },
  { title: 'PJ Masks', content_type: 'tv_show', popularity_rank: 36 },
  { title: 'Gabby\'s Dollhouse', content_type: 'tv_show', popularity_rank: 37 },
  { title: 'Spirit Rangers', content_type: 'tv_show', popularity_rank: 38 },
  { title: 'Ada Twist, Scientist', content_type: 'tv_show', popularity_rank: 39 },
  { title: 'Centaurworld', content_type: 'tv_show', popularity_rank: 40 },
  { title: 'Craig of the Creek', content_type: 'tv_show', popularity_rank: 41 },
  { title: 'We Bare Bears', content_type: 'tv_show', popularity_rank: 42 },
  { title: 'Star vs. the Forces of Evil', content_type: 'tv_show', popularity_rank: 43 },
  { title: 'The Simpsons', content_type: 'tv_show', popularity_rank: 44 },
  { title: 'Family Guy', content_type: 'tv_show', popularity_rank: 45 },
  { title: 'Bob\'s Burgers', content_type: 'tv_show', popularity_rank: 46 },
  { title: 'Big Mouth', content_type: 'tv_show', popularity_rank: 47 },
  { title: 'Arcane', content_type: 'tv_show', popularity_rank: 48 },
  { title: 'Invincible', content_type: 'tv_show', popularity_rank: 49 },
  { title: 'Demon Slayer', content_type: 'tv_show', popularity_rank: 50 },
  { title: 'My Hero Academia', content_type: 'tv_show', popularity_rank: 51 },
  { title: 'Naruto', content_type: 'tv_show', popularity_rank: 52 },
  { title: 'Dragon Ball Z', content_type: 'tv_show', popularity_rank: 53 },
  { title: 'Pokemon', content_type: 'tv_show', popularity_rank: 54 },
  { title: 'One Piece', content_type: 'tv_show', popularity_rank: 55 },
  { title: 'Attack on Titan', content_type: 'tv_show', popularity_rank: 56 },
  { title: 'Jujutsu Kaisen', content_type: 'tv_show', popularity_rank: 57 },
  { title: 'Spy x Family', content_type: 'tv_show', popularity_rank: 58 },
  { title: 'Hunter x Hunter', content_type: 'tv_show', popularity_rank: 59 },
  { title: 'Fullmetal Alchemist: Brotherhood', content_type: 'tv_show', popularity_rank: 60 },
  { title: 'The Mandalorian', content_type: 'tv_show', popularity_rank: 61 },
  { title: 'Ahsoka', content_type: 'tv_show', popularity_rank: 62 },
  { title: 'Loki', content_type: 'tv_show', popularity_rank: 63 },
  { title: 'WandaVision', content_type: 'tv_show', popularity_rank: 64 },
  { title: 'Ms. Marvel', content_type: 'tv_show', popularity_rank: 65 },
  { title: 'Moon Knight', content_type: 'tv_show', popularity_rank: 66 },
  { title: 'Young Sheldon', content_type: 'tv_show', popularity_rank: 67 },
  { title: 'Cobra Kai', content_type: 'tv_show', popularity_rank: 68 },
  { title: 'Gilmore Girls', content_type: 'tv_show', popularity_rank: 69 },
  { title: 'Good Luck Charlie', content_type: 'tv_show', popularity_rank: 70 },
  { title: 'Jessie', content_type: 'tv_show', popularity_rank: 71 },
  { title: 'Austin & Ally', content_type: 'tv_show', popularity_rank: 72 },
  { title: 'Wizards of Waverly Place', content_type: 'tv_show', popularity_rank: 73 },
  { title: 'Hannah Montana', content_type: 'tv_show', popularity_rank: 74 },
  { title: 'iCarly', content_type: 'tv_show', popularity_rank: 75 },
  { title: 'Victorious', content_type: 'tv_show', popularity_rank: 76 },
  { title: 'Sam & Cat', content_type: 'tv_show', popularity_rank: 77 },
  { title: 'Henry Danger', content_type: 'tv_show', popularity_rank: 78 },
  { title: 'The Thundermans', content_type: 'tv_show', popularity_rank: 79 },
  { title: 'Nicky, Ricky, Dicky & Dawn', content_type: 'tv_show', popularity_rank: 80 },
  { title: 'Game Shakers', content_type: 'tv_show', popularity_rank: 81 },
  { title: 'Danger Force', content_type: 'tv_show', popularity_rank: 82 },
  { title: 'That\'s So Raven', content_type: 'tv_show', popularity_rank: 83 },
  { title: 'Raven\'s Home', content_type: 'tv_show', popularity_rank: 84 },
  { title: 'Andi Mack', content_type: 'tv_show', popularity_rank: 85 },
  { title: 'Diary of a Future President', content_type: 'tv_show', popularity_rank: 86 },
  { title: 'High School Musical: The Musical: The Series', content_type: 'tv_show', popularity_rank: 87 },
  { title: 'Bunk\'d', content_type: 'tv_show', popularity_rank: 88 },
  { title: 'Sydney to the Max', content_type: 'tv_show', popularity_rank: 89 },
  { title: 'Just Roll with It', content_type: 'tv_show', popularity_rank: 90 },
  { title: 'Coop & Cami Ask the World', content_type: 'tv_show', popularity_rank: 91 },
  { title: 'BIOS', content_type: 'tv_show', popularity_rank: 92 },
  { title: 'Star Wars: The Clone Wars', content_type: 'tv_show', popularity_rank: 93 },
  { title: 'Star Wars: Rebels', content_type: 'tv_show', popularity_rank: 94 },
  { title: 'Star Wars: The Bad Batch', content_type: 'tv_show', popularity_rank: 95 },
  { title: 'DuckTales', content_type: 'tv_show', popularity_rank: 96 },
  { title: 'Chip \'n Dale: Rescue Rangers', content_type: 'tv_show', popularity_rank: 97 },
  { title: 'TaleSpin', content_type: 'tv_show', popularity_rank: 98 },
  { title: 'Darkwing Duck', content_type: 'tv_show', popularity_rank: 99 },
  { title: 'Kim Possible', content_type: 'tv_show', popularity_rank: 100 },

  // Movies (popularity_rank 201-500)
  { title: 'Frozen', content_type: 'movie', popularity_rank: 201 },
  { title: 'Frozen II', content_type: 'movie', popularity_rank: 202 },
  { title: 'Encanto', content_type: 'movie', popularity_rank: 203 },
  { title: 'Moana', content_type: 'movie', popularity_rank: 204 },
  { title: 'Coco', content_type: 'movie', popularity_rank: 205 },
  { title: 'Turning Red', content_type: 'movie', popularity_rank: 206 },
  { title: 'Luca', content_type: 'movie', popularity_rank: 207 },
  { title: 'Soul', content_type: 'movie', popularity_rank: 208 },
  { title: 'Toy Story', content_type: 'movie', popularity_rank: 209 },
  { title: 'Toy Story 2', content_type: 'movie', popularity_rank: 210 },
  { title: 'Toy Story 3', content_type: 'movie', popularity_rank: 211 },
  { title: 'Toy Story 4', content_type: 'movie', popularity_rank: 212 },
  { title: 'Finding Nemo', content_type: 'movie', popularity_rank: 213 },
  { title: 'Finding Dory', content_type: 'movie', popularity_rank: 214 },
  { title: 'The Incredibles', content_type: 'movie', popularity_rank: 215 },
  { title: 'Incredibles 2', content_type: 'movie', popularity_rank: 216 },
  { title: 'Inside Out', content_type: 'movie', popularity_rank: 217 },
  { title: 'Inside Out 2', content_type: 'movie', popularity_rank: 218 },
  { title: 'Up', content_type: 'movie', popularity_rank: 219 },
  { title: 'WALL-E', content_type: 'movie', popularity_rank: 220 },
  { title: 'Ratatouille', content_type: 'movie', popularity_rank: 221 },
  { title: 'Monsters, Inc.', content_type: 'movie', popularity_rank: 222 },
  { title: 'Monsters University', content_type: 'movie', popularity_rank: 223 },
  { title: 'Cars', content_type: 'movie', popularity_rank: 224 },
  { title: 'Cars 2', content_type: 'movie', popularity_rank: 225 },
  { title: 'Cars 3', content_type: 'movie', popularity_rank: 226 },
  { title: 'A Bug\'s Life', content_type: 'movie', popularity_rank: 227 },
  { title: 'Brave', content_type: 'movie', popularity_rank: 228 },
  { title: 'The Good Dinosaur', content_type: 'movie', popularity_rank: 229 },
  { title: 'Onward', content_type: 'movie', popularity_rank: 230 },
  { title: 'Elemental', content_type: 'movie', popularity_rank: 231 },
  { title: 'Lightyear', content_type: 'movie', popularity_rank: 232 },
  { title: 'The Lion King', content_type: 'movie', popularity_rank: 233 },
  { title: 'The Lion King (2019)', content_type: 'movie', popularity_rank: 234 },
  { title: 'The Little Mermaid', content_type: 'movie', popularity_rank: 235 },
  { title: 'The Little Mermaid (2023)', content_type: 'movie', popularity_rank: 236 },
  { title: 'Beauty and the Beast', content_type: 'movie', popularity_rank: 237 },
  { title: 'Aladdin', content_type: 'movie', popularity_rank: 238 },
  { title: 'Aladdin (2019)', content_type: 'movie', popularity_rank: 239 },
  { title: 'Tangled', content_type: 'movie', popularity_rank: 240 },
  { title: 'The Princess and the Frog', content_type: 'movie', popularity_rank: 241 },
  { title: 'Pocahontas', content_type: 'movie', popularity_rank: 242 },
  { title: 'Mulan', content_type: 'movie', popularity_rank: 243 },
  { title: 'Mulan (2020)', content_type: 'movie', popularity_rank: 244 },
  { title: 'Cinderella', content_type: 'movie', popularity_rank: 245 },
  { title: 'Sleeping Beauty', content_type: 'movie', popularity_rank: 246 },
  { title: 'Snow White and the Seven Dwarfs', content_type: 'movie', popularity_rank: 247 },
  { title: 'Hercules', content_type: 'movie', popularity_rank: 248 },
  { title: 'Tarzan', content_type: 'movie', popularity_rank: 249 },
  { title: 'The Jungle Book', content_type: 'movie', popularity_rank: 250 },
  { title: 'Shrek', content_type: 'movie', popularity_rank: 251 },
  { title: 'Shrek 2', content_type: 'movie', popularity_rank: 252 },
  { title: 'Shrek the Third', content_type: 'movie', popularity_rank: 253 },
  { title: 'Shrek Forever After', content_type: 'movie', popularity_rank: 254 },
  { title: 'Puss in Boots', content_type: 'movie', popularity_rank: 255 },
  { title: 'Puss in Boots: The Last Wish', content_type: 'movie', popularity_rank: 256 },
  { title: 'How to Train Your Dragon', content_type: 'movie', popularity_rank: 257 },
  { title: 'How to Train Your Dragon 2', content_type: 'movie', popularity_rank: 258 },
  { title: 'How to Train Your Dragon: The Hidden World', content_type: 'movie', popularity_rank: 259 },
  { title: 'Kung Fu Panda', content_type: 'movie', popularity_rank: 260 },
  { title: 'Kung Fu Panda 2', content_type: 'movie', popularity_rank: 261 },
  { title: 'Kung Fu Panda 3', content_type: 'movie', popularity_rank: 262 },
  { title: 'Kung Fu Panda 4', content_type: 'movie', popularity_rank: 263 },
  { title: 'Madagascar', content_type: 'movie', popularity_rank: 264 },
  { title: 'Madagascar: Escape 2 Africa', content_type: 'movie', popularity_rank: 265 },
  { title: 'Madagascar 3: Europe\'s Most Wanted', content_type: 'movie', popularity_rank: 266 },
  { title: 'The Croods', content_type: 'movie', popularity_rank: 267 },
  { title: 'The Croods: A New Age', content_type: 'movie', popularity_rank: 268 },
  { title: 'Trolls', content_type: 'movie', popularity_rank: 269 },
  { title: 'Trolls World Tour', content_type: 'movie', popularity_rank: 270 },
  { title: 'Trolls Band Together', content_type: 'movie', popularity_rank: 271 },
  { title: 'The Boss Baby', content_type: 'movie', popularity_rank: 272 },
  { title: 'The Boss Baby: Family Business', content_type: 'movie', popularity_rank: 273 },
  { title: 'Megamind', content_type: 'movie', popularity_rank: 274 },
  { title: 'Spirit: Stallion of the Cimarron', content_type: 'movie', popularity_rank: 275 },
  { title: 'Despicable Me', content_type: 'movie', popularity_rank: 276 },
  { title: 'Despicable Me 2', content_type: 'movie', popularity_rank: 277 },
  { title: 'Despicable Me 3', content_type: 'movie', popularity_rank: 278 },
  { title: 'Despicable Me 4', content_type: 'movie', popularity_rank: 279 },
  { title: 'Minions', content_type: 'movie', popularity_rank: 280 },
  { title: 'Minions: The Rise of Gru', content_type: 'movie', popularity_rank: 281 },
  { title: 'The Secret Life of Pets', content_type: 'movie', popularity_rank: 282 },
  { title: 'The Secret Life of Pets 2', content_type: 'movie', popularity_rank: 283 },
  { title: 'Sing', content_type: 'movie', popularity_rank: 284 },
  { title: 'Sing 2', content_type: 'movie', popularity_rank: 285 },
  { title: 'The Super Mario Bros. Movie', content_type: 'movie', popularity_rank: 286 },
  { title: 'Migration', content_type: 'movie', popularity_rank: 287 },
  { title: 'Spider-Man: Into the Spider-Verse', content_type: 'movie', popularity_rank: 288 },
  { title: 'Spider-Man: Across the Spider-Verse', content_type: 'movie', popularity_rank: 289 },
  { title: 'Harry Potter and the Sorcerer\'s Stone', content_type: 'movie', popularity_rank: 290 },
  { title: 'Harry Potter and the Chamber of Secrets', content_type: 'movie', popularity_rank: 291 },
  { title: 'Harry Potter and the Prisoner of Azkaban', content_type: 'movie', popularity_rank: 292 },
  { title: 'Harry Potter and the Goblet of Fire', content_type: 'movie', popularity_rank: 293 },
  { title: 'Harry Potter and the Order of the Phoenix', content_type: 'movie', popularity_rank: 294 },
  { title: 'Harry Potter and the Half-Blood Prince', content_type: 'movie', popularity_rank: 295 },
  { title: 'Harry Potter and the Deathly Hallows - Part 1', content_type: 'movie', popularity_rank: 296 },
  { title: 'Harry Potter and the Deathly Hallows - Part 2', content_type: 'movie', popularity_rank: 297 },
  { title: 'Fantastic Beasts and Where to Find Them', content_type: 'movie', popularity_rank: 298 },
  { title: 'Star Wars: A New Hope', content_type: 'movie', popularity_rank: 299 },
  { title: 'Star Wars: The Empire Strikes Back', content_type: 'movie', popularity_rank: 300 },
  { title: 'Star Wars: Return of the Jedi', content_type: 'movie', popularity_rank: 301 },
  { title: 'Star Wars: The Force Awakens', content_type: 'movie', popularity_rank: 302 },
  { title: 'Star Wars: The Last Jedi', content_type: 'movie', popularity_rank: 303 },
  { title: 'Star Wars: The Rise of Skywalker', content_type: 'movie', popularity_rank: 304 },
  { title: 'Rogue One: A Star Wars Story', content_type: 'movie', popularity_rank: 305 },
  { title: 'Solo: A Star Wars Story', content_type: 'movie', popularity_rank: 306 },
  { title: 'The Avengers', content_type: 'movie', popularity_rank: 307 },
  { title: 'Avengers: Age of Ultron', content_type: 'movie', popularity_rank: 308 },
  { title: 'Avengers: Infinity War', content_type: 'movie', popularity_rank: 309 },
  { title: 'Avengers: Endgame', content_type: 'movie', popularity_rank: 310 },
  { title: 'Black Panther', content_type: 'movie', popularity_rank: 311 },
  { title: 'Black Panther: Wakanda Forever', content_type: 'movie', popularity_rank: 312 },
  { title: 'Thor: Ragnarok', content_type: 'movie', popularity_rank: 313 },
  { title: 'Thor: Love and Thunder', content_type: 'movie', popularity_rank: 314 },
  { title: 'Guardians of the Galaxy', content_type: 'movie', popularity_rank: 315 },
  { title: 'Guardians of the Galaxy Vol. 2', content_type: 'movie', popularity_rank: 316 },
  { title: 'Guardians of the Galaxy Vol. 3', content_type: 'movie', popularity_rank: 317 },
  { title: 'Spider-Man: Homecoming', content_type: 'movie', popularity_rank: 318 },
  { title: 'Spider-Man: Far From Home', content_type: 'movie', popularity_rank: 319 },
  { title: 'Spider-Man: No Way Home', content_type: 'movie', popularity_rank: 320 },
  { title: 'Doctor Strange', content_type: 'movie', popularity_rank: 321 },
  { title: 'Doctor Strange in the Multiverse of Madness', content_type: 'movie', popularity_rank: 322 },
  { title: 'Ant-Man', content_type: 'movie', popularity_rank: 323 },
  { title: 'Ant-Man and the Wasp', content_type: 'movie', popularity_rank: 324 },
  { title: 'Ant-Man and the Wasp: Quantumania', content_type: 'movie', popularity_rank: 325 },
  { title: 'The Hunger Games', content_type: 'movie', popularity_rank: 326 },
  { title: 'The Hunger Games: Catching Fire', content_type: 'movie', popularity_rank: 327 },
  { title: 'The Hunger Games: Mockingjay - Part 1', content_type: 'movie', popularity_rank: 328 },
  { title: 'The Hunger Games: Mockingjay - Part 2', content_type: 'movie', popularity_rank: 329 },
  { title: 'The Hunger Games: The Ballad of Songbirds & Snakes', content_type: 'movie', popularity_rank: 330 },
  { title: 'Jurassic Park', content_type: 'movie', popularity_rank: 331 },
  { title: 'The Lost World: Jurassic Park', content_type: 'movie', popularity_rank: 332 },
  { title: 'Jurassic Park III', content_type: 'movie', popularity_rank: 333 },
  { title: 'Jurassic World', content_type: 'movie', popularity_rank: 334 },
  { title: 'Jurassic World: Fallen Kingdom', content_type: 'movie', popularity_rank: 335 },
  { title: 'Jurassic World Dominion', content_type: 'movie', popularity_rank: 336 },
  { title: 'E.T. the Extra-Terrestrial', content_type: 'movie', popularity_rank: 337 },
  { title: 'Home Alone', content_type: 'movie', popularity_rank: 338 },
  { title: 'Home Alone 2: Lost in New York', content_type: 'movie', popularity_rank: 339 },
  { title: 'The Wizard of Oz', content_type: 'movie', popularity_rank: 340 },
  { title: 'Charlie and the Chocolate Factory', content_type: 'movie', popularity_rank: 341 },
  { title: 'Wonka', content_type: 'movie', popularity_rank: 342 },
  { title: 'The Polar Express', content_type: 'movie', popularity_rank: 343 },
  { title: 'Elf', content_type: 'movie', popularity_rank: 344 },
  { title: 'The Nightmare Before Christmas', content_type: 'movie', popularity_rank: 345 },
  { title: 'Coraline', content_type: 'movie', popularity_rank: 346 },
  { title: 'Corpse Bride', content_type: 'movie', popularity_rank: 347 },
  { title: 'ParaNorman', content_type: 'movie', popularity_rank: 348 },
  { title: 'Hotel Transylvania', content_type: 'movie', popularity_rank: 349 },
  { title: 'Hotel Transylvania 2', content_type: 'movie', popularity_rank: 350 },
  { title: 'Hotel Transylvania 3: Summer Vacation', content_type: 'movie', popularity_rank: 351 },
  { title: 'Hotel Transylvania: Transformania', content_type: 'movie', popularity_rank: 352 },
  { title: 'The Addams Family', content_type: 'movie', popularity_rank: 353 },
  { title: 'The Addams Family 2', content_type: 'movie', popularity_rank: 354 },
  { title: 'Ghostbusters', content_type: 'movie', popularity_rank: 355 },
  { title: 'Ghostbusters: Afterlife', content_type: 'movie', popularity_rank: 356 },
  { title: 'Ghostbusters: Frozen Empire', content_type: 'movie', popularity_rank: 357 },
  { title: 'Goosebumps', content_type: 'movie', popularity_rank: 358 },
  { title: 'Goosebumps 2: Haunted Halloween', content_type: 'movie', popularity_rank: 359 },
  { title: 'Hocus Pocus', content_type: 'movie', popularity_rank: 360 },
  { title: 'Hocus Pocus 2', content_type: 'movie', popularity_rank: 361 },
  { title: 'Beetlejuice', content_type: 'movie', popularity_rank: 362 },
  { title: 'Beetlejuice Beetlejuice', content_type: 'movie', popularity_rank: 363 },
  { title: 'The LEGO Movie', content_type: 'movie', popularity_rank: 364 },
  { title: 'The LEGO Movie 2: The Second Part', content_type: 'movie', popularity_rank: 365 },
  { title: 'The LEGO Batman Movie', content_type: 'movie', popularity_rank: 366 },
  { title: 'The LEGO Ninjago Movie', content_type: 'movie', popularity_rank: 367 },
  { title: 'Ralph Breaks the Internet', content_type: 'movie', popularity_rank: 368 },
  { title: 'Wreck-It Ralph', content_type: 'movie', popularity_rank: 369 },
  { title: 'Big Hero 6', content_type: 'movie', popularity_rank: 370 },
  { title: 'Zootopia', content_type: 'movie', popularity_rank: 371 },
  { title: 'Raya and the Last Dragon', content_type: 'movie', popularity_rank: 372 },
  { title: 'Strange World', content_type: 'movie', popularity_rank: 373 },
  { title: 'Wish', content_type: 'movie', popularity_rank: 374 },
  { title: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', content_type: 'movie', popularity_rank: 375 },
  { title: 'The Chronicles of Narnia: Prince Caspian', content_type: 'movie', popularity_rank: 376 },
  { title: 'The Chronicles of Narnia: The Voyage of the Dawn Treader', content_type: 'movie', popularity_rank: 377 },
  { title: 'The Lord of the Rings: The Fellowship of the Ring', content_type: 'movie', popularity_rank: 378 },
  { title: 'The Lord of the Rings: The Two Towers', content_type: 'movie', popularity_rank: 379 },
  { title: 'The Lord of the Rings: The Return of the King', content_type: 'movie', popularity_rank: 380 },
  { title: 'The Hobbit: An Unexpected Journey', content_type: 'movie', popularity_rank: 381 },
  { title: 'The Hobbit: The Desolation of Smaug', content_type: 'movie', popularity_rank: 382 },
  { title: 'The Hobbit: The Battle of the Five Armies', content_type: 'movie', popularity_rank: 383 },
  { title: 'Night at the Museum', content_type: 'movie', popularity_rank: 384 },
  { title: 'Night at the Museum: Battle of the Smithsonian', content_type: 'movie', popularity_rank: 385 },
  { title: 'Night at the Museum: Secret of the Tomb', content_type: 'movie', popularity_rank: 386 },
  { title: 'Paddington', content_type: 'movie', popularity_rank: 387 },
  { title: 'Paddington 2', content_type: 'movie', popularity_rank: 388 },
  { title: 'Paddington in Peru', content_type: 'movie', popularity_rank: 389 },
  { title: 'The Peanuts Movie', content_type: 'movie', popularity_rank: 390 },
  { title: 'Ferdinand', content_type: 'movie', popularity_rank: 391 },
  { title: 'Ice Age', content_type: 'movie', popularity_rank: 392 },
  { title: 'Ice Age: The Meltdown', content_type: 'movie', popularity_rank: 393 },
  { title: 'Ice Age: Dawn of the Dinosaurs', content_type: 'movie', popularity_rank: 394 },
  { title: 'Ice Age: Continental Drift', content_type: 'movie', popularity_rank: 395 },
  { title: 'Ice Age: Collision Course', content_type: 'movie', popularity_rank: 396 },
  { title: 'Rio', content_type: 'movie', popularity_rank: 397 },
  { title: 'Rio 2', content_type: 'movie', popularity_rank: 398 },
  { title: 'The Emoji Movie', content_type: 'movie', popularity_rank: 399 },
  { title: 'Angry Birds', content_type: 'movie', popularity_rank: 400 },

  // Books (popularity_rank 501-800)
  { title: 'Harry Potter and the Sorcerer\'s Stone', content_type: 'book', popularity_rank: 501 },
  { title: 'Harry Potter and the Chamber of Secrets', content_type: 'book', popularity_rank: 502 },
  { title: 'Harry Potter and the Prisoner of Azkaban', content_type: 'book', popularity_rank: 503 },
  { title: 'Harry Potter and the Goblet of Fire', content_type: 'book', popularity_rank: 504 },
  { title: 'Harry Potter and the Order of the Phoenix', content_type: 'book', popularity_rank: 505 },
  { title: 'Harry Potter and the Half-Blood Prince', content_type: 'book', popularity_rank: 506 },
  { title: 'Harry Potter and the Deathly Hallows', content_type: 'book', popularity_rank: 507 },
  { title: 'Diary of a Wimpy Kid', content_type: 'book', popularity_rank: 508 },
  { title: 'Diary of a Wimpy Kid: Rodrick Rules', content_type: 'book', popularity_rank: 509 },
  { title: 'Diary of a Wimpy Kid: The Last Straw', content_type: 'book', popularity_rank: 510 },
  { title: 'Diary of a Wimpy Kid: Dog Days', content_type: 'book', popularity_rank: 511 },
  { title: 'Diary of a Wimpy Kid: The Ugly Truth', content_type: 'book', popularity_rank: 512 },
  { title: 'Captain Underpants', content_type: 'book', popularity_rank: 513 },
  { title: 'Dog Man', content_type: 'book', popularity_rank: 514 },
  { title: 'Cat Kid Comic Club', content_type: 'book', popularity_rank: 515 },
  { title: 'Percy Jackson and the Lightning Thief', content_type: 'book', popularity_rank: 516 },
  { title: 'Percy Jackson and the Sea of Monsters', content_type: 'book', popularity_rank: 517 },
  { title: 'Percy Jackson and the Titan\'s Curse', content_type: 'book', popularity_rank: 518 },
  { title: 'Percy Jackson and the Battle of the Labyrinth', content_type: 'book', popularity_rank: 519 },
  { title: 'Percy Jackson and the Last Olympian', content_type: 'book', popularity_rank: 520 },
  { title: 'The Heroes of Olympus: The Lost Hero', content_type: 'book', popularity_rank: 521 },
  { title: 'Magnus Chase and the Gods of Asgard', content_type: 'book', popularity_rank: 522 },
  { title: 'The Kane Chronicles: The Red Pyramid', content_type: 'book', popularity_rank: 523 },
  { title: 'The Hunger Games', content_type: 'book', popularity_rank: 524 },
  { title: 'Catching Fire', content_type: 'book', popularity_rank: 525 },
  { title: 'Mockingjay', content_type: 'book', popularity_rank: 526 },
  { title: 'The Ballad of Songbirds and Snakes', content_type: 'book', popularity_rank: 527 },
  { title: 'Divergent', content_type: 'book', popularity_rank: 528 },
  { title: 'Insurgent', content_type: 'book', popularity_rank: 529 },
  { title: 'Allegiant', content_type: 'book', popularity_rank: 530 },
  { title: 'The Maze Runner', content_type: 'book', popularity_rank: 531 },
  { title: 'The Scorch Trials', content_type: 'book', popularity_rank: 532 },
  { title: 'The Death Cure', content_type: 'book', popularity_rank: 533 },
  { title: 'The Giver', content_type: 'book', popularity_rank: 534 },
  { title: 'Gathering Blue', content_type: 'book', popularity_rank: 535 },
  { title: 'Messenger', content_type: 'book', popularity_rank: 536 },
  { title: 'Son', content_type: 'book', popularity_rank: 537 },
  { title: 'Wonder', content_type: 'book', popularity_rank: 538 },
  { title: 'Auggie & Me', content_type: 'book', popularity_rank: 539 },
  { title: 'Charlotte\'s Web', content_type: 'book', popularity_rank: 540 },
  { title: 'Stuart Little', content_type: 'book', popularity_rank: 541 },
  { title: 'The Trumpet of the Swan', content_type: 'book', popularity_rank: 542 },
  { title: 'James and the Giant Peach', content_type: 'book', popularity_rank: 543 },
  { title: 'Charlie and the Chocolate Factory', content_type: 'book', popularity_rank: 544 },
  { title: 'Matilda', content_type: 'book', popularity_rank: 545 },
  { title: 'The BFG', content_type: 'book', popularity_rank: 546 },
  { title: 'The Witches', content_type: 'book', popularity_rank: 547 },
  { title: 'The Twits', content_type: 'book', popularity_rank: 548 },
  { title: 'Fantastic Mr. Fox', content_type: 'book', popularity_rank: 549 },
  { title: 'George\'s Marvellous Medicine', content_type: 'book', popularity_rank: 550 },
  { title: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', content_type: 'book', popularity_rank: 551 },
  { title: 'The Chronicles of Narnia: Prince Caspian', content_type: 'book', popularity_rank: 552 },
  { title: 'The Chronicles of Narnia: The Voyage of the Dawn Treader', content_type: 'book', popularity_rank: 553 },
  { title: 'The Chronicles of Narnia: The Silver Chair', content_type: 'book', popularity_rank: 554 },
  { title: 'The Chronicles of Narnia: The Horse and His Boy', content_type: 'book', popularity_rank: 555 },
  { title: 'The Chronicles of Narnia: The Magician\'s Nephew', content_type: 'book', popularity_rank: 556 },
  { title: 'The Chronicles of Narnia: The Last Battle', content_type: 'book', popularity_rank: 557 },
  { title: 'A Wrinkle in Time', content_type: 'book', popularity_rank: 558 },
  { title: 'A Wind in the Door', content_type: 'book', popularity_rank: 559 },
  { title: 'A Swiftly Tilting Planet', content_type: 'book', popularity_rank: 560 },
  { title: 'Bridge to Terabithia', content_type: 'book', popularity_rank: 561 },
  { title: 'Holes', content_type: 'book', popularity_rank: 562 },
  { title: 'Hatchet', content_type: 'book', popularity_rank: 563 },
  { title: 'My Side of the Mountain', content_type: 'book', popularity_rank: 564 },
  { title: 'Island of the Blue Dolphins', content_type: 'book', popularity_rank: 565 },
  { title: 'Number the Stars', content_type: 'book', popularity_rank: 566 },
  { title: 'The Outsiders', content_type: 'book', popularity_rank: 567 },
  { title: 'Tuck Everlasting', content_type: 'book', popularity_rank: 568 },
  { title: 'Coraline', content_type: 'book', popularity_rank: 569 },
  { title: 'The Graveyard Book', content_type: 'book', popularity_rank: 570 },
  { title: 'Good Omens', content_type: 'book', popularity_rank: 571 },
  { title: 'Stardust', content_type: 'book', popularity_rank: 572 },
  { title: 'The Hobbit', content_type: 'book', popularity_rank: 573 },
  { title: 'The Fellowship of the Ring', content_type: 'book', popularity_rank: 574 },
  { title: 'The Two Towers', content_type: 'book', popularity_rank: 575 },
  { title: 'The Return of the King', content_type: 'book', popularity_rank: 576 },
  { title: 'Eragon', content_type: 'book', popularity_rank: 577 },
  { title: 'Eldest', content_type: 'book', popularity_rank: 578 },
  { title: 'Brisingr', content_type: 'book', popularity_rank: 579 },
  { title: 'Inheritance', content_type: 'book', popularity_rank: 580 },
  { title: 'Twilight', content_type: 'book', popularity_rank: 581 },
  { title: 'New Moon', content_type: 'book', popularity_rank: 582 },
  { title: 'Eclipse', content_type: 'book', popularity_rank: 583 },
  { title: 'Breaking Dawn', content_type: 'book', popularity_rank: 584 },
  { title: 'Midnight Sun', content_type: 'book', popularity_rank: 585 },
  { title: 'The Fault in Our Stars', content_type: 'book', popularity_rank: 586 },
  { title: 'Looking for Alaska', content_type: 'book', popularity_rank: 587 },
  { title: 'Paper Towns', content_type: 'book', popularity_rank: 588 },
  { title: 'Turtles All the Way Down', content_type: 'book', popularity_rank: 589 },
  { title: 'An Abundance of Katherines', content_type: 'book', popularity_rank: 590 },
  { title: 'The Hate U Give', content_type: 'book', popularity_rank: 591 },
  { title: 'Children of Blood and Bone', content_type: 'book', popularity_rank: 592 },
  { title: 'Simon vs. the Homo Sapiens Agenda', content_type: 'book', popularity_rank: 593 },
  { title: 'Red, White & Royal Blue', content_type: 'book', popularity_rank: 594 },
  { title: 'Heartstopper', content_type: 'book', popularity_rank: 595 },
  { title: 'The House in the Cerulean Sea', content_type: 'book', popularity_rank: 596 },
  { title: 'Aristotle and Dante Discover the Secrets of the Universe', content_type: 'book', popularity_rank: 597 },
  { title: 'I\'ll Give You the Sun', content_type: 'book', popularity_rank: 598 },
  { title: 'They Both Die at the End', content_type: 'book', popularity_rank: 599 },
  { title: 'What If It\'s Us', content_type: 'book', popularity_rank: 600 },
  { title: 'The Perks of Being a Wallflower', content_type: 'book', popularity_rank: 601 },
  { title: 'Thirteen Reasons Why', content_type: 'book', popularity_rank: 602 },
  { title: 'Speak', content_type: 'book', popularity_rank: 603 },
  { title: 'If I Stay', content_type: 'book', popularity_rank: 604 },
  { title: 'Where She Went', content_type: 'book', popularity_rank: 605 },
  { title: 'Five Feet Apart', content_type: 'book', popularity_rank: 606 },
  { title: 'To All the Boys I\'ve Loved Before', content_type: 'book', popularity_rank: 607 },
  { title: 'P.S. I Still Love You', content_type: 'book', popularity_rank: 608 },
  { title: 'Always and Forever, Lara Jean', content_type: 'book', popularity_rank: 609 },
  { title: 'The Summer I Turned Pretty', content_type: 'book', popularity_rank: 610 },
  { title: 'It\'s Not Summer Without You', content_type: 'book', popularity_rank: 611 },
  { title: 'We\'ll Always Have Summer', content_type: 'book', popularity_rank: 612 },
  { title: 'Anna and the French Kiss', content_type: 'book', popularity_rank: 613 },
  { title: 'Lola and the Boy Next Door', content_type: 'book', popularity_rank: 614 },
  { title: 'Isla and the Happily Ever After', content_type: 'book', popularity_rank: 615 },
  { title: 'Eleanor & Park', content_type: 'book', popularity_rank: 616 },
  { title: 'Fangirl', content_type: 'book', popularity_rank: 617 },
  { title: 'Carry On', content_type: 'book', popularity_rank: 618 },
  { title: 'Wayward Son', content_type: 'book', popularity_rank: 619 },
  { title: 'Any Way the Wind Blows', content_type: 'book', popularity_rank: 620 },
  { title: 'The Baby-Sitters Club', content_type: 'book', popularity_rank: 621 },
  { title: 'Goosebumps', content_type: 'book', popularity_rank: 622 },
  { title: 'Fear Street', content_type: 'book', popularity_rank: 623 },
  { title: 'Animorphs', content_type: 'book', popularity_rank: 624 },
  { title: 'A Series of Unfortunate Events: The Bad Beginning', content_type: 'book', popularity_rank: 625 },
  { title: 'A Series of Unfortunate Events: The Reptile Room', content_type: 'book', popularity_rank: 626 },
  { title: 'A Series of Unfortunate Events: The Wide Window', content_type: 'book', popularity_rank: 627 },
  { title: 'Junie B. Jones', content_type: 'book', popularity_rank: 628 },
  { title: 'Magic Tree House', content_type: 'book', popularity_rank: 629 },
  { title: 'The Magic School Bus', content_type: 'book', popularity_rank: 630 },
  { title: 'Geronimo Stilton', content_type: 'book', popularity_rank: 631 },
  { title: 'Big Nate', content_type: 'book', popularity_rank: 632 },
  { title: 'Dork Diaries', content_type: 'book', popularity_rank: 633 },
  { title: 'The Bad Guys', content_type: 'book', popularity_rank: 634 },
  { title: 'Wings of Fire', content_type: 'book', popularity_rank: 635 },
  { title: 'Warriors', content_type: 'book', popularity_rank: 636 },
  { title: 'Keeper of the Lost Cities', content_type: 'book', popularity_rank: 637 },
  { title: 'The Land of Stories', content_type: 'book', popularity_rank: 638 },
  { title: 'The Unwanteds', content_type: 'book', popularity_rank: 639 },
  { title: 'Miss Peregrine\'s Home for Peculiar Children', content_type: 'book', popularity_rank: 640 },
  { title: 'Hollow City', content_type: 'book', popularity_rank: 641 },
  { title: 'Library of Souls', content_type: 'book', popularity_rank: 642 },
  { title: 'The City of Ember', content_type: 'book', popularity_rank: 643 },
  { title: 'The People of Sparks', content_type: 'book', popularity_rank: 644 },
  { title: 'Gregor the Overlander', content_type: 'book', popularity_rank: 645 },
  { title: 'Where the Wild Things Are', content_type: 'book', popularity_rank: 646 },
  { title: 'Goodnight Moon', content_type: 'book', popularity_rank: 647 },
  { title: 'The Very Hungry Caterpillar', content_type: 'book', popularity_rank: 648 },
  { title: 'Green Eggs and Ham', content_type: 'book', popularity_rank: 649 },
  { title: 'The Cat in the Hat', content_type: 'book', popularity_rank: 650 },
  { title: 'Oh, the Places You\'ll Go!', content_type: 'book', popularity_rank: 651 },
  { title: 'How the Grinch Stole Christmas!', content_type: 'book', popularity_rank: 652 },
  { title: 'The Lorax', content_type: 'book', popularity_rank: 653 },
  { title: 'Horton Hears a Who!', content_type: 'book', popularity_rank: 654 },
  { title: 'One Fish Two Fish Red Fish Blue Fish', content_type: 'book', popularity_rank: 655 },
  { title: 'The Giving Tree', content_type: 'book', popularity_rank: 656 },
  { title: 'Where the Sidewalk Ends', content_type: 'book', popularity_rank: 657 },
  { title: 'A Light in the Attic', content_type: 'book', popularity_rank: 658 },
  { title: 'The Polar Express', content_type: 'book', popularity_rank: 659 },
  { title: 'Corduroy', content_type: 'book', popularity_rank: 660 },
  { title: 'Curious George', content_type: 'book', popularity_rank: 661 },
  { title: 'If You Give a Mouse a Cookie', content_type: 'book', popularity_rank: 662 },
  { title: 'The Rainbow Fish', content_type: 'book', popularity_rank: 663 },
  { title: 'Love You Forever', content_type: 'book', popularity_rank: 664 },
  { title: 'Guess How Much I Love You', content_type: 'book', popularity_rank: 665 },
  { title: 'The Snowy Day', content_type: 'book', popularity_rank: 666 },
  { title: 'Harold and the Purple Crayon', content_type: 'book', popularity_rank: 667 },
  { title: 'Chicka Chicka Boom Boom', content_type: 'book', popularity_rank: 668 },
  { title: 'Brown Bear, Brown Bear, What Do You See?', content_type: 'book', popularity_rank: 669 },
  { title: 'The Snowy Day', content_type: 'book', popularity_rank: 670 },
  { title: 'Llama Llama Red Pajama', content_type: 'book', popularity_rank: 671 },
  { title: 'Pete the Cat', content_type: 'book', popularity_rank: 672 },
  { title: 'Elephant & Piggie', content_type: 'book', popularity_rank: 673 },
  { title: 'The Pigeon', content_type: 'book', popularity_rank: 674 },
  { title: 'Knuffle Bunny', content_type: 'book', popularity_rank: 675 },
  { title: 'Dragons Love Tacos', content_type: 'book', popularity_rank: 676 },
  { title: 'The Day the Crayons Quit', content_type: 'book', popularity_rank: 677 },
  { title: 'The Day the Crayons Came Home', content_type: 'book', popularity_rank: 678 },
  { title: 'Last Stop on Market Street', content_type: 'book', popularity_rank: 679 },
  { title: 'The Word Collector', content_type: 'book', popularity_rank: 680 },
  { title: 'The Dot', content_type: 'book', popularity_rank: 681 },
  { title: 'Ish', content_type: 'book', popularity_rank: 682 },
  { title: 'Sky Color', content_type: 'book', popularity_rank: 683 },
  { title: 'Giraffes Can\'t Dance', content_type: 'book', popularity_rank: 684 },
  { title: 'The Gruffalo', content_type: 'book', popularity_rank: 685 },
  { title: 'Room on the Broom', content_type: 'book', popularity_rank: 686 },
  { title: 'Stick Man', content_type: 'book', popularity_rank: 687 },
  { title: 'The Snail and the Whale', content_type: 'book', popularity_rank: 688 },
  { title: 'Zog', content_type: 'book', popularity_rank: 689 },
  { title: 'The Smartest Giant in Town', content_type: 'book', popularity_rank: 690 },
  { title: 'A Squash and a Squeeze', content_type: 'book', popularity_rank: 691 },
  { title: 'We\'re Going on a Bear Hunt', content_type: 'book', popularity_rank: 692 },
  { title: 'Dear Zoo', content_type: 'book', popularity_rank: 693 },
  { title: 'Each Peach Pear Plum', content_type: 'book', popularity_rank: 694 },
  { title: 'Owl Babies', content_type: 'book', popularity_rank: 695 },
  { title: 'The Tiger Who Came to Tea', content_type: 'book', popularity_rank: 696 },
  { title: 'Mog the Forgetful Cat', content_type: 'book', popularity_rank: 697 },
  { title: 'Dogger', content_type: 'book', popularity_rank: 698 },
  { title: 'Not Now, Bernard', content_type: 'book', popularity_rank: 699 },
  { title: 'Funnybones', content_type: 'book', popularity_rank: 700 }
];

const seed = async () => {
  try {
    console.log('Seeding autocomplete_titles table...');

    // Clear existing data
    await db.query('DELETE FROM autocomplete_titles');
    console.log('✓ Cleared existing data');

    // Insert seed data in batches
    const batchSize = 50;
    for (let i = 0; i < seedData.length; i += batchSize) {
      const batch = seedData.slice(i, i + batchSize);
      const values = batch.map((_, idx) => {
        const offset = i + idx;
        return `($${offset * 3 + 1}, $${offset * 3 + 2}, $${offset * 3 + 3})`;
      });

      const params = batch.flatMap(item => [item.title, item.content_type, item.popularity_rank]);

      // Use individual inserts for simplicity
      for (const item of batch) {
        await db.query(
          `INSERT INTO autocomplete_titles (title, content_type, popularity_rank)
           VALUES ($1, $2, $3)
           ON CONFLICT (title, content_type) DO UPDATE SET popularity_rank = $3`,
          [item.title, item.content_type, item.popularity_rank]
        );
      }

      console.log(`✓ Inserted batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(seedData.length / batchSize)}`);
    }

    console.log(`\n✅ Successfully seeded ${seedData.length} titles!`);
    console.log(`   - TV Shows: ${seedData.filter(t => t.content_type === 'tv_show').length}`);
    console.log(`   - Movies: ${seedData.filter(t => t.content_type === 'movie').length}`);
    console.log(`   - Books: ${seedData.filter(t => t.content_type === 'book').length}`);

    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  }
};

seed();
